---
# tasks file for tomcat
- name: install tomcat
  become: yes
  apt:
        name: tomcat8
        state: present

- name: Copy from build server to deploy server
  hosts: "{{groups['build'][0]}}"
  user: devops
  become: 'yes'
#  shell: scp devops@192.168.1.106:/tmp/prj/target/hello-1.0.war /tmp
#; cp ~/hello-1.0.war /var/lib/tomcat8/webapps/
  synchronize:
        src: /tmp/prj/target/hello-1.0.war
        dest: /var/lib/tomcat8/webapps/
        mode: pull
  delegate_to: "{{groups['deploy'][0]}}"

#  synchronize:
#    mode: pull
#    src: rsync://devops@192.168.1.106:/tmp/prj/target/hello-1.0.war
#    dest: /var/lib/tomcat8/webapps/
#  delegate_to: localhost

- name: Restart Tomcat
  become: 'yes'
  service:
    name: tomcat8
    state: restarted
