---
# tasks file for tomcat
- name: install tomcat
  become: yes
  apt:
        name: tomcat8
        state: present

- name: copy war from master to tomcat
  become: 'yes'
  copy:
    src: ./hello-1.0.war
    dest: /var/lib/tomcat8/webapps/
    remote_src: 'no'

- name: Restart Tomcat
  become: 'yes'
  service:
    name: tomcat8
    state: restarted
